title: Andrew Wisecarver
logo: "/images/Penguin.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  example text.
  <br><br>
  <a href="https://www.linkedin.com/in/andrew-wisecarver/">View My LinkedIn Profile</a> 
  # <br><br>
  # <a href="https://www.kaggle.com/gabrielmadigan">View My Kaggle Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-YGEBZFD2F1
